import crypto from 'node:crypto';
import { calculatePriorityScore, classifyPriority, weightedAverage, StudyPriority } from '../services/studentStudyPriority';

type Db = any;
type ProfileInput = Partial<{ displayName: string; institution: string; campus: string; course: string; schoolYear: string; className: string; shift: string; availableTimeJson: string; onboardingCompleted: boolean }>;
type SubjectInput = { name: string; category?: string; source?: string };
type GradeInput = { subjectId: string; periodId?: string | null; assessmentName: string; score: number; weight?: number; source?: string; isUncertain?: boolean };
type ExamInput = { subjectId?: string | null; name: string; examDate: string; examTime?: string | null; weight?: number; targetGrade?: number | null; topics?: string[]; notes?: string; room?: string; status?: string };
type EventInput = { eventType: string; title: string; eventDate: string; startTime?: string; endTime?: string; examId?: string | null; notes?: string };

const DEFAULT_SUBJECTS = ['Matemática', 'Física', 'Química', 'Biologia', 'Português', 'Literatura', 'Redação', 'História', 'Geografia', 'Filosofia', 'Sociologia', 'Inglês', 'Espanhol', 'Artes', 'Educação Física', 'Informática'];

const isoNow = () => new Date().toISOString();
const parseJson = <T>(value: unknown, fallback: T): T => { try { return value ? JSON.parse(String(value)) as T : fallback; } catch { return fallback; } };
const rowProfile = (r: any) => r && ({ id: r.id, userId: r.user_id, displayName: r.display_name, institution: r.institution, campus: r.campus, course: r.course, schoolYear: r.school_year, className: r.class_name, shift: r.shift, availableTimeJson: r.available_time_json, onboardingCompleted: Boolean(r.onboarding_completed), createdAt: r.created_at, updatedAt: r.updated_at });
const rowSubject = (r: any) => r && ({ id: r.id, userId: r.user_id, name: r.name, category: r.category, source: r.source, active: Boolean(r.active), createdAt: r.created_at, updatedAt: r.updated_at });
const rowGrade = (r: any) => r && ({ id: r.id, userId: r.user_id, subjectId: r.subject_id, subjectName: r.subject_name, periodId: r.period_id, periodName: r.period_name, assessmentName: r.assessment_name, score: Number(r.score), weight: Number(r.weight), source: r.source, isUncertain: Boolean(r.is_uncertain), createdAt: r.created_at, updatedAt: r.updated_at });
const rowExam = (r: any) => r && ({ id: r.id, userId: r.user_id, subjectId: r.subject_id, subjectName: r.subject_name, name: r.name, examDate: r.exam_date, examTime: r.exam_time, weight: Number(r.weight), targetGrade: r.target_grade == null ? null : Number(r.target_grade), topics: parseJson<string[]>(r.topics_json, []), notes: r.notes, room: r.room, status: r.status, createdAt: r.created_at, updatedAt: r.updated_at });
const rowEvent = (r: any) => ({ id: r.id, userId: r.user_id, eventType: r.event_type, title: r.title, eventDate: r.event_date, startTime: r.start_time, endTime: r.end_time, examId: r.exam_id, notes: r.notes, createdAt: r.created_at, updatedAt: r.updated_at });

export class StudentStudyRepository {
  constructor(private db: Db) {}

  ensureDefaults(userId: string): void {
    const existing = Number((this.db.prepare('SELECT COUNT(*) AS count FROM student_subjects WHERE user_id = ?').get(userId) as any)?.count || 0);
    if (!existing) {
      const now = isoNow();
      for (const name of DEFAULT_SUBJECTS) this.db.prepare('INSERT INTO student_subjects (id, user_id, name, category, source, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)').run(crypto.randomUUID(), userId, name, 'escola', 'default', now, now);
    }
    const periods = Number((this.db.prepare('SELECT COUNT(*) AS count FROM student_academic_periods WHERE user_id = ?').get(userId) as any)?.count || 0);
    if (!periods) {
      const now = isoNow();
      ['1º Bimestre', '2º Bimestre', '3º Bimestre', '4º Bimestre'].forEach((name, index) => this.db.prepare('INSERT INTO student_academic_periods (id, user_id, name, sort_order, created_at) VALUES (?, ?, ?, ?, ?)').run(crypto.randomUUID(), userId, name, index, now));
    }
  }

  getProfile(userId: string): any {
    return rowProfile(this.db.prepare('SELECT * FROM student_profiles WHERE user_id = ?').get(userId));
  }

  upsertProfile(userId: string, input: ProfileInput): any {
    const now = isoNow();
    const current = this.getProfile(userId);
    const values = { displayName: String(input.displayName ?? current?.displayName ?? '').slice(0, 120), institution: String(input.institution ?? current?.institution ?? 'IFRJ').slice(0, 120), campus: input.campus == null ? current?.campus ?? null : String(input.campus).slice(0, 120), course: input.course == null ? current?.course ?? null : String(input.course).slice(0, 160), schoolYear: input.schoolYear == null ? current?.schoolYear ?? null : String(input.schoolYear).slice(0, 80), className: input.className == null ? current?.className ?? null : String(input.className).slice(0, 80), shift: input.shift == null ? current?.shift ?? null : String(input.shift).slice(0, 40), availableTimeJson: input.availableTimeJson == null ? current?.availableTimeJson ?? null : String(input.availableTimeJson).slice(0, 8000), onboardingCompleted: input.onboardingCompleted == null ? Boolean(current?.onboardingCompleted) : Boolean(input.onboardingCompleted) };
    if (current) this.db.prepare('UPDATE student_profiles SET display_name=?, institution=?, campus=?, course=?, school_year=?, class_name=?, shift=?, available_time_json=?, onboarding_completed=?, updated_at=? WHERE user_id=?').run(values.displayName, values.institution, values.campus, values.course, values.schoolYear, values.className, values.shift, values.availableTimeJson, values.onboardingCompleted ? 1 : 0, now, userId);
    else this.db.prepare('INSERT INTO student_profiles (id,user_id,display_name,institution,campus,course,school_year,class_name,shift,available_time_json,onboarding_completed,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(crypto.randomUUID(), userId, values.displayName, values.institution, values.campus, values.course, values.schoolYear, values.className, values.shift, values.availableTimeJson, values.onboardingCompleted ? 1 : 0, now, now);
    return this.getProfile(userId);
  }

  listSubjects(userId: string): any[] { return (this.db.prepare('SELECT * FROM student_subjects WHERE user_id = ? AND active = 1 ORDER BY name').all(userId) as any[]).map(rowSubject); }
  getSubject(userId: string, id: string): any { return rowSubject(this.db.prepare('SELECT * FROM student_subjects WHERE user_id = ? AND id = ? AND active = 1').get(userId, id)) || null; }
  createSubject(userId: string, input: SubjectInput): any { const now = isoNow(); const id = crypto.randomUUID(); this.db.prepare('INSERT INTO student_subjects (id,user_id,name,category,source,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(id, userId, input.name.trim().slice(0, 120), input.category || 'custom', input.source || 'custom', now, now); return this.getSubject(userId, id); }
  updateSubject(userId: string, id: string, input: Partial<SubjectInput>): any { const current = this.getSubject(userId, id); if (!current) return null; this.db.prepare('UPDATE student_subjects SET name=?, category=?, updated_at=? WHERE user_id=? AND id=?').run(String(input.name ?? current.name).trim().slice(0, 120), String(input.category ?? current.category).slice(0, 40), isoNow(), userId, id); return this.getSubject(userId, id); }
  deleteSubject(userId: string, id: string): boolean { const result = this.db.prepare('UPDATE student_subjects SET active=0, updated_at=? WHERE user_id=? AND id=?').run(isoNow(), userId, id); return Number(result.changes) > 0; }
  listTopics(userId: string, subjectId: string): any[] { return this.db.prepare('SELECT id, user_id AS userId, subject_id AS subjectId, name, created_at AS createdAt FROM student_subject_topics WHERE user_id=? AND subject_id=? ORDER BY name').all(userId, subjectId) as any[]; }
  createTopic(userId: string, subjectId: string, name: string): any { const id=crypto.randomUUID(); this.db.prepare('INSERT INTO student_subject_topics (id,user_id,subject_id,name,created_at) VALUES (?,?,?,?,?)').run(id,userId,subjectId,name.trim().slice(0,120),isoNow()); return this.db.prepare('SELECT id,user_id AS userId,subject_id AS subjectId,name,created_at AS createdAt FROM student_subject_topics WHERE user_id=? AND id=?').get(userId,id); }
  deleteTopic(userId: string, id: string): boolean { const result=this.db.prepare('DELETE FROM student_subject_topics WHERE user_id=? AND id=?').run(userId,id); return Number(result.changes)>0; }

  listPeriods(userId: string): any[] { return this.db.prepare('SELECT id, user_id AS userId, name, sort_order AS sortOrder, starts_at AS startsAt, ends_at AS endsAt, active FROM student_academic_periods WHERE user_id=? AND active=1 ORDER BY sort_order, name').all(userId) as any[]; }
  private hasPeriod(userId: string, periodId?: string | null): boolean { return !periodId || Boolean(this.db.prepare('SELECT 1 FROM student_academic_periods WHERE user_id=? AND id=? AND active=1').get(userId, periodId)); }

  listGrades(userId: string): any[] { return (this.db.prepare('SELECT g.*, s.name AS subject_name, p.name AS period_name FROM student_grades g JOIN student_subjects s ON s.id=g.subject_id AND s.user_id=g.user_id LEFT JOIN student_academic_periods p ON p.id=g.period_id AND p.user_id=g.user_id WHERE g.user_id=? ORDER BY s.name, g.created_at DESC').all(userId) as any[]).map(rowGrade); }
  getGrade(userId: string, id: string): any { const r = this.db.prepare('SELECT g.*, s.name AS subject_name, p.name AS period_name FROM student_grades g JOIN student_subjects s ON s.id=g.subject_id AND s.user_id=g.user_id LEFT JOIN student_academic_periods p ON p.id=g.period_id AND p.user_id=g.user_id WHERE g.user_id=? AND g.id=?').get(userId, id); return rowGrade(r) || null; }
  createGrade(userId: string, input: GradeInput): any { const subject = this.getSubject(userId, input.subjectId); if (!subject || !this.hasPeriod(userId, input.periodId)) return null; const id = crypto.randomUUID(); const now = isoNow(); this.db.prepare('INSERT INTO student_grades (id,user_id,subject_id,period_id,assessment_name,score,weight,source,is_uncertain,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(id,userId,input.subjectId,input.periodId || null,input.assessmentName.trim().slice(0,120),input.score,input.weight ?? 1,input.source || 'manual',input.isUncertain ? 1 : 0,now,now); return this.getGrade(userId,id); }
  updateGrade(userId: string, id: string, input: Partial<GradeInput>): any { const current = this.getGrade(userId,id); if (!current) return null; const subjectId = input.subjectId || current.subjectId; const periodId = input.periodId === undefined ? current.periodId : input.periodId; if (!this.getSubject(userId,subjectId) || !this.hasPeriod(userId, periodId)) return null; this.db.prepare('UPDATE student_grades SET subject_id=?, period_id=?, assessment_name=?, score=?, weight=?, source=?, is_uncertain=?, updated_at=? WHERE user_id=? AND id=?').run(subjectId,periodId,input.assessmentName === undefined ? current.assessmentName : String(input.assessmentName).trim().slice(0,120),input.score === undefined ? current.score : input.score,input.weight === undefined ? current.weight : input.weight,input.source || current.source,input.isUncertain === undefined ? (current.isUncertain ? 1 : 0) : (input.isUncertain ? 1 : 0),isoNow(),userId,id); return this.getGrade(userId,id); }
  deleteGrade(userId: string, id: string): boolean { const result = this.db.prepare('DELETE FROM student_grades WHERE user_id=? AND id=?').run(userId,id); return Number(result.changes) > 0; }

  listExams(userId: string): any[] { return (this.db.prepare('SELECT e.*, s.name AS subject_name FROM student_exams e LEFT JOIN student_subjects s ON s.id=e.subject_id AND s.user_id=e.user_id WHERE e.user_id=? ORDER BY e.exam_date, e.exam_time').all(userId) as any[]).map(rowExam); }
  getExam(userId: string, id: string): any { const r = this.db.prepare('SELECT e.*, s.name AS subject_name FROM student_exams e LEFT JOIN student_subjects s ON s.id=e.subject_id AND s.user_id=e.user_id WHERE e.user_id=? AND e.id=?').get(userId,id); return rowExam(r) || null; }
  createExam(userId: string, input: ExamInput): any { if (input.subjectId && !this.getSubject(userId,input.subjectId)) return null; const id=crypto.randomUUID(), now=isoNow(); this.db.prepare('INSERT INTO student_exams (id,user_id,subject_id,name,exam_date,exam_time,weight,target_grade,topics_json,notes,room,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,userId,input.subjectId || null,input.name.trim().slice(0,160),input.examDate,input.examTime || null,input.weight ?? 1,input.targetGrade ?? null,JSON.stringify((input.topics || []).slice(0,40).map((x) => String(x).slice(0,120))),input.notes ? String(input.notes).slice(0,2000) : null,input.room ? String(input.room).slice(0,120) : null,input.status || 'planned',now,now); return this.getExam(userId,id); }
  updateExam(userId: string,id:string,input:Partial<ExamInput>):any { const current=this.getExam(userId,id); if(!current)return null; const subjectId=input.subjectId===undefined?current.subjectId:input.subjectId; if(subjectId&&!this.getSubject(userId,subjectId))return null; this.db.prepare('UPDATE student_exams SET subject_id=?,name=?,exam_date=?,exam_time=?,weight=?,target_grade=?,topics_json=?,notes=?,room=?,status=?,updated_at=? WHERE user_id=? AND id=?').run(subjectId,input.name===undefined?current.name:String(input.name).trim().slice(0,160),input.examDate||current.examDate,input.examTime===undefined?current.examTime:input.examTime,input.weight===undefined?current.weight:input.weight,input.targetGrade===undefined?current.targetGrade:input.targetGrade,JSON.stringify(input.topics===undefined?current.topics:input.topics),input.notes===undefined?current.notes:input.notes,input.room===undefined?current.room:input.room,input.status||current.status,isoNow(),userId,id); return this.getExam(userId,id); }
  deleteExam(userId:string,id:string):boolean { const result=this.db.prepare('DELETE FROM student_exams WHERE user_id=? AND id=?').run(userId,id); return Number(result.changes)>0; }

  listEvents(userId: string): any[] { return (this.db.prepare('SELECT * FROM student_calendar_events WHERE user_id=? ORDER BY event_date,start_time,title').all(userId) as any[]).map(rowEvent); }
  createEvent(userId:string,input:EventInput):any { if(input.examId&&!this.getExam(userId,input.examId))return null; const id=crypto.randomUUID(),now=isoNow(); this.db.prepare('INSERT INTO student_calendar_events (id,user_id,event_type,title,event_date,start_time,end_time,exam_id,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(id,userId,input.eventType,input.title.trim().slice(0,160),input.eventDate,input.startTime||null,input.endTime||null,input.examId||null,input.notes?String(input.notes).slice(0,2000):null,now,now); return rowEvent(this.db.prepare('SELECT * FROM student_calendar_events WHERE user_id=? AND id=?').get(userId,id)); }
  deleteEvent(userId:string,id:string):boolean { const result=this.db.prepare('DELETE FROM student_calendar_events WHERE user_id=? AND id=?').run(userId,id); return Number(result.changes)>0; }

  listGoals(userId:string):any[] { const goals:any[]=this.db.prepare('SELECT * FROM student_goals WHERE user_id=? AND status=\'active\' ORDER BY created_at DESC').all(userId); return goals.map((g)=>({...g,id:g.id,userId:g.user_id,degree:g.degree,selectionSystem:g.selection_system,institutions:this.db.prepare('SELECT institution_name AS name,institution_code AS code,state,city FROM student_goal_institutions WHERE user_id=? AND goal_id=?').all(userId,g.id)})); }
  createGoal(userId:string,input:{degree:string;selectionSystem:string;institutions?:Array<{name:string;code?:string;state?:string;city?:string}>}):any { const id=crypto.randomUUID(),now=isoNow(); this.db.prepare('INSERT INTO student_goals (id,user_id,degree,selection_system,created_at,updated_at) VALUES (?,?,?,?,?,?)').run(id,userId,input.degree.trim().slice(0,160),input.selectionSystem.slice(0,60),now,now); for(const item of (input.institutions||[]).slice(0,20))this.db.prepare('INSERT INTO student_goal_institutions (id,user_id,goal_id,institution_name,institution_code,state,city) VALUES (?,?,?,?,?,?,?)').run(crypto.randomUUID(),userId,id,String(item.name).slice(0,160),item.code||null,item.state||null,item.city||null); return this.listGoals(userId).find((g)=>g.id===id); }

  createReportCard(userId:string,fileId:string,periodId?:string|null):any { if (!this.hasPeriod(userId, periodId)) return null; const id=crypto.randomUUID(),now=isoNow(); this.db.prepare('INSERT INTO student_report_cards (id,user_id,file_id,period_id,created_at,updated_at) VALUES (?,?,?,?,?,?)').run(id,userId,fileId,periodId||null,now,now); return {id,userId,fileId,periodId:periodId||null,status:'uploaded',createdAt:now}; }
  saveAnalysis(userId:string,type:string,summary:string,structured:any):any { const id=crypto.randomUUID(),now=isoNow(); this.db.prepare('INSERT INTO student_ai_analyses (id,user_id,analysis_type,summary,structured_json,created_at) VALUES (?,?,?,?,?,?)').run(id,userId,type,summary.slice(0,4000),structured?JSON.stringify(structured):null,now); return {id,userId,type,summary,structured,createdAt:now}; }
  listAnalyses(userId:string):any[] { return (this.db.prepare('SELECT id,user_id,analysis_type,summary,structured_json,created_at FROM student_ai_analyses WHERE user_id=? ORDER BY created_at DESC LIMIT 30').all(userId) as any[]).map((r)=>({id:r.id,userId:r.user_id,type:r.analysis_type,summary:r.summary,structured:parseJson(r.structured_json,null),createdAt:r.created_at})); }

  reserveAiRequest(userId:string,limits:{requests:number;reports?:number},isReport=false):boolean { const day=new Date().toISOString().slice(0,10); this.db.prepare('INSERT INTO student_ai_usage (user_id,usage_date) VALUES (?,?) ON CONFLICT(user_id,usage_date) DO NOTHING').run(userId,day); const column=isReport?'report_count':'request_count'; const max=isReport?(limits.reports??limits.requests):limits.requests; const result=this.db.prepare(`UPDATE student_ai_usage SET ${column}=${column}+1 WHERE user_id=? AND usage_date=? AND ${column} < ?`).run(userId,day,max); return Number(result.changes)>0; }
  usage(userId:string):any { const day=new Date().toISOString().slice(0,10); return this.db.prepare('SELECT request_count AS requests,report_count AS reports,input_tokens AS inputTokens,output_tokens AS outputTokens FROM student_ai_usage WHERE user_id=? AND usage_date=?').get(userId,day) || {requests:0,reports:0,inputTokens:0,outputTokens:0}; }

  searchInstitutions(userId:string,query:string,limit=25,offset=0):any[] { void userId; const q=`%${query.trim().slice(0,80)}%`; return this.db.prepare('SELECT id,name,acronym,mec_code AS mecCode,state,city,institution_type AS institutionType,administrative_category AS administrativeCategory,status FROM university_institutions WHERE status=\'active\' AND (name LIKE ? OR acronym LIKE ? OR state LIKE ? OR city LIKE ?) ORDER BY name LIMIT ? OFFSET ?').all(q,q,q,q,Math.min(100,Math.max(1,limit)),Math.max(0,offset)) as any[]; }
  searchCourses(userId:string,query:string,limit=25,offset=0):any[] { void userId; const q=`%${query.trim().slice(0,80)}%`; return this.db.prepare('SELECT c.id,c.name,c.degree_type AS degreeType,c.modality,c.status,c.mec_code AS mecCode,i.id AS institutionId,i.name AS institutionName,i.acronym,i.state,i.city FROM university_courses c JOIN university_institutions i ON i.id=c.institution_id WHERE c.status=\'active\' AND (c.name LIKE ? OR i.name LIKE ? OR i.acronym LIKE ?) ORDER BY c.name LIMIT ? OFFSET ?').all(q,q,q,Math.min(100,Math.max(1,limit)),Math.max(0,offset)) as any[]; }

  dashboard(userId:string):any {
    this.ensureDefaults(userId);
    const subjects=this.listSubjects(userId), grades=this.listGrades(userId), exams=this.listExams(userId), events=this.listEvents(userId), goals=this.listGoals(userId), profile=this.getProfile(userId);
    const today=Date.now();
    const performance=subjects.map((subject)=>{ const subjectGrades=grades.filter((g)=>g.subjectId===subject.id); const average=weightedAverage(subjectGrades); const next=exams.find((e)=>e.subjectId===subject.id&&e.status==='planned'&&new Date(`${e.examDate}T23:59:59`).getTime()>=today); const days=next?Math.ceil((new Date(`${next.examDate}T23:59:59`).getTime()-today)/86400000):null; const score=calculatePriorityScore({currentAverage:average??0,targetGrade:next?.targetGrade,daysUntilExam:days,examWeight:next?.weight,difficulty:average==null?5:Math.max(0,10-(average)),vestibularWeight:goals.length?5:0}); return {...subject,average,gradesCount:subjectGrades.length,nextExam:next?{id:next.id,name:next.name,date:next.examDate,daysRemaining:days}:null,priorityScore:score,priority:classifyPriority(score)}; }).sort((a,b)=>b.priorityScore-a.priorityScore);
    const enrichedExams = exams.map((exam) => {
      const daysRemaining = Math.ceil((new Date(`${exam.examDate}T23:59:59`).getTime() - today) / 86400000);
      const currentAverage = performance.find((item) => item.id === exam.subjectId)?.average ?? 0;
      const score = calculatePriorityScore({ currentAverage, targetGrade: exam.targetGrade, daysUntilExam: daysRemaining, examWeight: exam.weight });
      return { ...exam, daysRemaining, priority: classifyPriority(score), priorityScore: score };
    });
    return { profile, subjects, periods: this.listPeriods(userId), grades, exams: enrichedExams, events, goals, performance, analyses: this.listAnalyses(userId), usage: this.usage(userId) };
  }
}
