import React, { useEffect, useState } from 'react';
import { AppTheme } from '../types';
import { BarChart3, TrendingDown } from 'lucide-react';

type Analytics = { summary: { attempts: number; correct: number; accuracyPercent: number; averageResponseSeconds: number | null; simulationsCreated: number; simulationsCompleted: number }; daily: Array<{ day: string; accuracyPercent: number; attempts: number }>; weakTopics: Array<{ discipline: string; topic: string; subtopic: string; accuracyPercent: number; attempts: number }> };

export const StudentAnalyticsPanel: React.FC<{ theme: AppTheme }> = ({ theme }) => {
  const dark = theme === 'dark';
  const [analytics, setAnalytics] = useState<Analytics | null>(null);
  useEffect(() => { fetch('/api/student/analytics?days=30', { headers: { Authorization: `Bearer ${localStorage.getItem('cfo_terminal_session') || ''}` } }).then((response) => response.json()).then((data) => setAnalytics(data.summary ? data : null)).catch(() => undefined); }, []);
  if (!analytics) return null;
  return <section className={`mb-5 rounded-2xl border p-5 ${dark ? 'border-slate-800 bg-[#0B1528]' : 'border-slate-200 bg-white'}`}><div className="flex items-center gap-2"><BarChart3 className="h-4 w-4 text-cyan-400" /><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-cyan-400">Release 5 · Analytics</p><h2 className={`mt-1 text-lg font-black ${dark ? 'text-white' : 'text-slate-900'}`}>Evolução dos últimos 30 dias</h2></div></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{[['Tentativas', analytics.summary.attempts], ['Acerto', `${analytics.summary.accuracyPercent}%`], ['Tempo médio', analytics.summary.averageResponseSeconds == null ? '—' : `${analytics.summary.averageResponseSeconds}s`], ['Simulados', analytics.summary.simulationsCompleted], ['Questões certas', analytics.summary.correct]].map(([label, value]) => <div key={String(label)} className={`rounded-xl border p-3 ${dark ? 'border-slate-800 bg-slate-950/40' : 'border-slate-100 bg-slate-50'}`}><p className="text-[10px] uppercase text-slate-500">{label}</p><p className={`mt-1 text-xl font-black ${dark ? 'text-white' : 'text-slate-900'}`}>{value}</p></div>)}</div><div className="mt-4 grid gap-4 md:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Atividade diária</p><div className="mt-2 flex h-24 items-end gap-1">{analytics.daily.slice(-14).map((day) => <div key={day.day} title={`${day.day}: ${day.accuracyPercent}%`} className="flex-1 rounded-t bg-cyan-500/70" style={{ height: `${Math.max(8, day.accuracyPercent)}%` }} />)}</div></div><div><p className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-rose-300"><TrendingDown className="h-3 w-3" /> Pontos de atenção</p><div className="mt-2 space-y-2">{analytics.weakTopics.slice(0, 4).map((topic) => <div key={`${topic.discipline}-${topic.topic}-${topic.subtopic}`} className="flex items-center justify-between gap-2 text-xs"><span className={dark ? 'text-slate-300' : 'text-slate-700'}>{topic.topic}</span><strong className="text-rose-300">{topic.accuracyPercent}%</strong></div>)}</div></div></div></section>;
};
